TECH-574 added converted project to typescript
TrellisCommerce/react-components pull request #13
Opened 2022-07-31 12:26 UTC by ikhoaA

2022-08-01 14:47 UTC, loan-laux requested changes
Looking pretty good @ikhoaA! A few requests for you — most of which will be solved by running Prettier on this branch. Also, please make sure to commit the new `package-lock.json`. Could you also explain why we're building for both CJS and ESM? Just curious about this approach as I'm not an expert on TS. Thanks!

2022-08-01 14:47 UTC, loan-laux commented on lib/ImageGallery/ImageGallery.tsx
> +  const handleThumbnailChange = (index: any) => {
Isn't the `index` a `number`?

2022-08-01 14:47 UTC, loan-laux commented on lib/utils/types.ts
> +}
Make sure to leave a blank line at the end of every file as best practice to comply with [POSIX standards](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)

2022-08-02 09:33 UTC, ikhoaA commented on package.json
> +    "build:esm": "node_modules/typescript/bin//tsc --preserveWatchOutput --jsx react-jsx",
resolved!

2022-08-02 09:34 UTC, ikhoaA commented on lib/Button/Button.tsx
> +  OverrideClasses?: boolean
Resolved

2022-08-02 09:57 UTC, ikhoaA commented
> 

Hi @loan-laux , the reason for building both CJS and ESM versions of the code is our package to be easily used for vanilla JavaScript and TypeScript.

2022-08-02 17:08 UTC, loan-laux requested changes
All good, thanks! Only one request: please rename `OverrideClasses` to `overrideClasses` throughout this branch. I'll instantly merge when done. Great work @ikhoaA!

2022-08-03 10:26 UTC, loan-laux approved these changes
Looking good! Thanks @ikhoaA

2022-08-03 10:26 UTC, merged